apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
spec:
  containers:
  - name: c0
    image: quay.io/crio/busybox:latest
    command:
      - sh
      - -c
      - sleep 3600
    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 100m
        memory: 100M
    imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 1
